### ISSUE TITLE
StatusScope bug

### ISSUE THREAD

**Issue by s16er1um** [EugeneShae/engine#26]
Описание бага:
Некорректная работа языковых версий слайдера при "Disable" статусе основной языковой версии.

Как выявить проблему:
1. Добавить слайдер на нескольких языковых версиях. Слайдер должен быть обязательно добавлен на дефолтном языке приложения.
2. На основной версии поставить статус "Disable", на вторичных "Enable".
3. Убедиться в отсутствии слайдера на домашней странице при любой (не основной) локализации приложения.

Техническое описание проблемы и способы решения:
1. В методе isStatusTranslatable() следует принимать модель, а так же передавать её при вызове из метода apply.
2. Свойство $translatable является protected свойством модели и не доступно при обращении через $this->translatable. Альтернативой является $model->getTranslatableAttributes().
3. $model->getTranslatableAttributes() возвращает массив с числовыми значениями ключей, поэтому вместо функции array_key_exists('status', $this->translatable) логично использовать 
in_array('status', $model->getTranslatableAttributes())

Версия класса прикреплённая ниже работает корректно:
[StatusScope.zip](https://github.com/EugeneShae/engine/files/3165652/StatusScope.zip)

**Comment by EugeneShae** [comment]
[Fix StatusScope for models, when status translatable](https://github.com/EugeneShae/engine/pull/30)
