### ISSUE TITLE
Bug with menu

### ISSUE THREAD

**Issue by s16er1um** [EugeneShae/engine#32]
**Describe the bug**
Не корректное название пункта меню

**To Reproduce**
1. Перейти на главную страницу проекта.
2. Открыть немецкую или итальянскую версию странички.
3. Навести (в некоторых случаях кликнуть) курсор мышки на пункт меню "Plattform".
4. После этого можно увидеть не корректный перевод пункта меню, который на английском выглядит как MetaTrader4 Mobile

**Expected behavior**
Проблема связана с не корректным стринговым значением в файле engine/stubs/menu-items.php для данного пункта меню.
Для решения проблемы нужно поменять значение для it и de версий меню.
Корректная итальянская версия - MetaTrader4 Mobile
Корректная немецкая версия - Mobiler MetaTrader4

**Comment by EugeneShae** [comment]
[](url)
