### ISSUE TITLE
Баг с Terms and Conditions

### ISSUE THREAD

**Issue by s16er1um** [EugeneShae/engine#42]
Переменная в админ панели которая отвечает за урлу для документов Terms and Conditions теперь имеет другое название. 
В связи с этим под формами регистрации и демо-регистрации не отображается корректная ссылка для перехода на документ

**Comment by koterion** [comment]
Переменная которая отвечала за ссылку на "Terms and Conditions " на старых брендах не правильная, а именно privacy-policy. При подключении пакета нужно менять на terms-conditions.
