### ISSUE TITLE
Баг при добавлении добавлении дополнительного "meta tag" - а на страницу

### ISSUE THREAD

**Issue by OlegFilinskiy** [EugeneShae/engine#56]
**Describe the bug**
При добавлении дополнительного "meta tag"-а на страницу через @slot('meta', '') он вставляется строкой в двойных кавычках.

**To Reproduce**
1. Идем во 'views/home/index.blade.php'
2. Добавляем @slot('meta','<meta name="interkassa-verification" content="e29b8b20c3d58ae0ce2371f487a704c4" />')
3. На главной странице видим вывод тэга не как разметки, а как строки.
4. Открываем консоль видим, что тэг выводится в двойных кавычках. 

**Expected behavior**
Из-за того что в файле layouts/index.blade.php вставка тэга происходит через строковый метод {{$meta ?? ''}} и происходит данный Баг. Необходимо заменить вывод тега, как разметки следующим методом: {!! $meta ?? '' !!}.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/25343306/63691385-b8b23300-c817-11e9-9e4f-59801f840b16.png)

**Comment by koterion** [comment]
Для вывода meta тегов используйте конструкцию `@slot` `@endslot`
